### ISSUE TITLE
Keylogger not sending anything

### ISSUE THREAD

**Issue by Shxw** [I2rys/ODiscord#1]
I tried the keylogger, it successfully injects into the wanted folder in the index.js file with the right webhook, the only problem is, no data is sent.

**Comment by I2rys** [comment]
Hello @Shxw,
Can you please send the Keylogger code that you setup as well as the code on the wanted index.js file here so I can look for the problem & fix it immediately.

If you want to send it privately, please DM me on discord. SucY#3048

**Comment by I2rys** [comment]
Hello again @Shxw,
Please check the [Keylogger](https://github.com/I2rys/ODiscord/tree/main/Keylogger) again because I fixed some bugs and removed curl because curl is not default on windows 10 It might be the cause of the problem that's why It's not sending anything because you don't have curl installed in your computer.
